# Docker Compose Configuration
# visit https://docs.docker.com/compose/

version: '3.8'
services:
  # app service for your backend
  app:
    container_name: nestjs-app
    build:
      context: ./
      dockerfile: Dockerfile
      target: builder
    command: npm run start:dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_NAME: nestjs_template
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_PORT: 3306
      DATABASE_HOST: host.docker.internal
    ports:
      - '3000:3000'
    depends_on:
      - database

  # start the mysql service as container
  database:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'nestjs_template'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - nestjs_container:/var/lib/mysql

volumes:
  nestjs_container:
